=== zaufi/team-expense-calc/tests/tec.dtd
<!ELEMENT arrangement (title?, members, currencies, events)>
<!ATTLIST arrangement
    version NMTOKEN "1.0"
    xmlns CDATA #FIXED 'http://code.google.com/p/team-expense-calc/#tec'
    >

    <!ELEMENT title (#PCDATA)>

    <!ELEMENT members (member+)>

        <!ELEMENT member (#PCDATA)>
        <!ATTLIST member id ID #REQUIRED>

    <!ELEMENT currencies (currency+)>

        <!ELEMENT currency (name, xchg*)>
        <!ATTLIST currency
            id ID #REQUIRED
            native (true|false) #IMPLIED
            >

        <!ELEMENT name (#PCDATA)>

        <!ELEMENT xchg (#PCDATA)>
        <!ATTLIST xchg
            to IDREF #REQUIRED
            value CDATA #IMPLIED
            >

    <!ELEMENT events (event+)>

        <!ELEMENT event (text, used-currency, participant+)>

        <!ELEMENT text (#PCDATA)>

        <!ELEMENT used-currency (#PCDATA)>
        <!ATTLIST used-currency id IDREF #REQUIRED>

        <!ELEMENT participant (#PCDATA)>
        <!ATTLIST participant
            id IDREF #REQUIRED
            payment CDATA #IMPLIED
            spent CDATA #IMPLIED
            >

=== zaufi/team-expense-calc/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tec:arrangement SYSTEM "tec.dtd">
<?xml-stylesheet type="text/xsl" href="tec.xsl"?>

<arrangement xmlns="http://code.google.com/p/team-expense-calc/#tec" version="1.0">

    <title>New Year Snowboarding Session 2009 (Ã…re, Sweeden)</title>

    <currencies>
        <currency id="rur" native="true">
            <name>RUR</name>
            <xchg to="rur" value="1">1</xchg>
        </currency>
        <currency id="eur">
            <name>EUR</name>
            <xchg to="rur" value="1">34.4975</xchg>
            <xchg to="usd" value="1">1.2</xchg>
        </currency>
        <currency id="sek">
            <name>SEK</name>
            <xchg to="rur" value="10">33.5461</xchg>
        </currency>
        <currency id="usd">
            <name>USD</name>
            <xchg to="rur" value="1">27,5715</xchg>
        </currency>
    </currencies>

    <!-- People who was on NY2k9 vacation -->
    <members>
        <member id="b">Barser</member>
        <member id="d" comment="Diman+Svetko">Diman</member>
        <member id="i">Ilich</member>
        <member id="m" comment="Kiruho+Julia">Megasos</member>
        <member id="z">Zaufi</member>
        <member id="v">Vanus</member>
    </members>

    <events>

        <event>
            <text>Alcohol from duty-free shop (Finland border)</text>
            <used-currency id="rur" />
            <participant id="z" payment="12000" />
            <participant id="b" />
            <participant id="d" />
            <participant id="m" />
            <participant id="v" />
        </event>

        <event>
            <text>Gas for Barser</text>
            <used-currency id="eur" />
            <!-- Ppl in a 1st car -->
            <participant id="b" payment="120" />
            <participant id="m" spent="80" />
        </event>

        <event>
            <text>Gas for Diman</text>
            <used-currency id="eur" />
            <!-- Ppl in a 2nd car -->
            <participant id="d" payment="120" spent="80"/>
            <participant id="z" />
        </event>

        <event>
            <text>Gas for Vanus</text>
            <used-currency id="eur" />
            <!-- Ppl in a 3rd car -->
            <participant id="v" payment="150" spent="100" />
            <participant id="i" />
        </event>

        <event>
            <text>Visit to cafeteria</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>

        <event>
            <text>Test event 1</text>
            <used-currency id="eur" />
            <participant id="i" payment="250" spent="10" />
            <participant id="v" spent="40" />
            <participant id="z" spent="10" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        
        <event>
            <text>Test event 2</text>
            <used-currency id="rur" />
            <participant id="i" payment="270" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="70" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 3</text>
            <used-currency id="usd" />
            <participant id="i" payment="90" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="200" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 4</text>
            <used-currency id="sek" />
            <participant id="i" payment="110" spent="15" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="10" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 5</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 6</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 7</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 8</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 9</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 10</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 11</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 12</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 13</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 14</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
        <event>
            <text>Test event 15</text>
            <used-currency id="eur" />
            <participant id="i" payment="100" spent="20" />
            <participant id="v" spent="40" />
            <participant id="z" payment="100" spent="25" />
            <participant id="d" spent="40" />
            <participant id="b" spent="20" />
            <participant id="m" spent="44" />
        </event>
    </events>

</arrangement>

=== zaufi/team-expense-calc/tests/example-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tec:arrangement SYSTEM "tec.dtd">
<?xml-stylesheet type="text/xsl" href="tec-ut.xsl"?>

<arrangement xmlns="http://code.google.com/p/team-expense-calc/#tec" version="1.0">

    <title>New Year Snowboarding Session 2009 (Ã„re, Sweeden)</title>

    <!-- People who was on NY2k9 vacation -->
    <members>
        <member id="z">Zaufi</member>
        <member id="b">Barser</member>
        <member id="d">Diman</member>
        <member id="m">Megasos</member>
        <member id="s">Sergio</member>
    </members>

    <currencies>
        <currency id="rur" native="true">
            <name>RUR</name>
        </currency>
        <currency id="eur">
            <name>EUR</name>
            <xchg to="rur" value="1">34.4975</xchg>
        </currency>
        <currency id="sek">
            <name>SEK</name>
            <xchg to="rur" value="1">3.35461</xchg>
        </currency>
        <currency id="usd">
            <name>USD</name>
            <xchg to="rur" value="1">27,5715</xchg>
        </currency>
    </currencies>

    <events>

        <event>
            <text>Alcohol from duty-free shop (Finland border)</text>
            <used-currency id="rur" />
            <participants>
                <participant id="z" payment="8500" />
                <participant id="b" payment="0" />
                <participant id="d" payment="0" />
                <participant id="m" payment="0" />
                <participant id="s" payment="0" />
            </participants>
        </event>
        <event>
            <text>Some food from duty-free shop (Finland border)</text>
            <used-currency id="rur" />
            <participants>
                <participant id="z" payment="0" />
                <participant id="b" payment="1100" />
                <participant id="d" payment="1500" />
                <participant id="m" payment="1000" />
                <participant id="s" payment="0" />
            </participants>
        </event>

        <event>
            <text>Dinner at ship</text>
            <used-currency id="eur" />
            <participants>
                <participant id="b" payment="100" />
                <participant id="d" payment="100" />
                <participant id="z" payment="0" />
                <participant id="m" payment="50" />
                <participant id="s" payment="0" />
            </participants>
        </event>

        <event>
            <text>Gas for Barser</text>
            <used-currency id="sek" />
            <participants>
                <participant id="b" payment="100" />
                <participant id="m" payment="0" />
                <participant id="s" payment="0" />
            </participants>
        </event>

        <event>
            <text>Gas for Diman</text>
            <used-currency id="sek" />
            <participants>
                <participant id="d" payment="100" />
                <participant id="z" payment="0" />
            </participants>
        </event>

    </events>

</arrangement>
